# Generated by Django 5.1.7 on 2025-03-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blog_category_alter_blog_author_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
    ]
